$(document).ready(function(){
    $("#design-pic").click(function(){
        $("#design-p").show();
        $("design-pic").hide();
    });
    $("#design-p").click(function(){
        $("#design-p").hide();
        $("#design-pic").show();
    });    
})